version: '3'
services:
  redis:
    image: redis:6.0.10
    volumes:
       - redis_data:/data
    ports:
      - "6379:6379"
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    ports:
      - "3306:3306"
volumes:
  redis_data:
  mysql_data:
